services:
  app:
    container_name: together-app
    working_dir: /src/app/back
    depends_on:
      - postgres
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      APP_MODE: ${APP_MODE:-development}
      PORT: ${PORT:-8080}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-app}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      JWT_KEY: ${JWT_KEY:-secret}
      FLUTTER_BUILD_PATH: ${FLUTTER_BUILD_PATH:-../front/build}
    env_file:
      - .env
    volumes:
      - "./:/src/app"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
