services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      PORT: ${PORT:-8080}
    volumes:
      - "./:/src/app"
