services:
#  app:
#    build: .
#    ports:
#      - "${PORT:-8080}:8080"
#    environment:
#      PORT: ${PORT:-8080}

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
