name: Back deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/esgi-together-challenge
        username: ${{ secrets.SCALEWAY_REGISTRY_USERNAME }}
        password: ${{ secrets.SCALEWAY_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: back
        push: true
        tags: rg.fr-par.scw.cloud/esgi-together-challenge/back:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Use CLI
      uses: scaleway/action-scw@v0
      with:
        save-config: true
        export-config: true
        version: v2.27.0
        access-key: ${{ secrets.SCALEWAY_REGISTRY_USERNAME }}
        secret-key: ${{ secrets.SCALEWAY_REGISTRY_PASSWORD }}
        default-project-id: ${{ vars.SCALEWAY_DEFAULT_PROJECT_ID }}
        default-organization-id: ${{ vars.SCALEWAY_DEFAULT_ORGANIZATION_ID }}

    - name: Deploy container
      uses: scaleway/action-scw@v0
      id: cli
      with:
        args: container container deploy ${{ vars.CONTAINER_ID }}
    - run: echo ${{ steps.cli.outputs.json }}
