name: Run tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy environment file
        run: cp .env.example .env

      - name: Run Docker container
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec app go mod download

      - name: Tidy up dependencies
        run: docker-compose exec app go mod tidy

      - name: Run tests
        run: docker-compose exec app go test -v ./...
